name: aoc
channels:
- conda-forge
- defaults
dependencies:
- bleach=2.0.0=py36_0
- certifi=2017.11.5=py36_0
- colorama=0.3.9=py36_0
- decorator=4.1.2=py36_0
- entrypoints=0.2.3=py36_1
- html5lib=0.999999999=py36_0
- ipykernel=4.6.1=py36_0
- ipython=6.2.1=py36_0
- ipython_genutils=0.2.0=py36_0
- jedi=0.10.2=py36_0
- jinja2=2.10=py36_0
- jsonschema=2.5.1=py36_0
- jupyter_client=5.1.0=py36_0
- jupyter_core=4.4.0=py_0
- markupsafe=1.0=py36_0
- mistune=0.8=py36_0
- nbconvert=5.3.1=py_1
- nbformat=4.4.0=py36_0
- notebook=5.2.2=py36_1
- pandoc=2.0.3=0
- pandocfilters=1.4.1=py36_0
- pickleshare=0.7.4=py36_0
- pip=9.0.1=py36_0
- prompt_toolkit=1.0.15=py36_0
- pygments=2.2.0=py36_0
- python=3.6.3=1
- python-dateutil=2.6.1=py36_0
- pyzmq=16.0.2=py36_2
- setuptools=38.2.3=py36_0
- simplegeneric=0.8.1=py36_0
- six=1.11.0=py36_1
- testpath=0.3.1=py36_0
- tornado=4.5.2=py36_0
- traitlets=4.3.2=py36_0
- vs2015_runtime=14.0.25420=0
- wcwidth=0.1.7=py36_0
- webencodings=0.5=py36_0
- wheel=0.30.0=py_1
- wincertstore=0.2=py36_0
- pip:
  - chardet==3.0.4
  - idna==2.6
  - ipython-genutils==0.2.0
  - jupyter-client==5.1.0
  - jupyter-core==4.4.0
  - prompt-toolkit==1.0.15
  - requests==2.18.4
  - urllib3==1.22
